### ISSUE TITLE
New Roadmap for V1.0

### ISSUE THREAD

**Issue by DaluS** [DaluS/GEMMES#69]
This is an update of #48 , with the list of things to do : 

## On core 

- [x] Integrate new `_def_fields`
- [x] Integrate fields from model (with a warning)
- [x] Add the enveloppe-cycle analysis (PR #72, parrallel system missing)
- [x] get_summary give a final value if run is done (PR #73)
- [x] Integrate new formalism of models
- [ ] Integrate vectors of values (parrallel) 
- [x] Tranform cycle analysis into a for loop for each systems

## On solvers

- [ ] Check the validity or results

## On models

- [ ] Having coping with collapse
- [ ] Having a CES ( full and reduced )

## On cockpit / GEMMES

- [ ] Check that every properties are available 

# To prepare `V1.X`

- Prepare writing for multisectorial 
- Prepare PDE 
- Prepare DDE 
- Prepare stochastic terms
- Prepare exterior binding
- Automatic dimensionless variables detection
- Solve fixed point intermediary functions 
- Check equation dimensions 
- Auxilliary variables 
- A generator of models based on stock-flow consistency and behavior equations ?
- Adding the bibliography
- Do a basin of attraction overlay 
- Do a finding equilibrium program

**Comment by DaluS** [comment]
See the WhatToDoNext.ipynb
